# Allows the running of the site in a subdirectory on Github Pages
# Note - if you enable this, and attempt to view your site locally you have to 
# pass the  --baseurl parameter when serving as an empty string e.g jekyll serve --baseurl ''
# http://jekyllrb.com/docs/github-pages/
baseurl : ""
relative_permalinks: false

# General settings
permalink: pretty
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    parse_block_html: true
    syntax_highlighter: rouge

# Name of the website
name: "ImageProcessor"
altname : "ImageProcessor.Web"

# Short description (goes below the title)
description: "A C# library for the dynamic processing of image files with .NET. ImageProcessor can resize, rotate, crop, flip, fade, watermark and add Instagram style filters to images."

# Your name, as you want it to appear underneath each post and in the footer
author: "James South"

version: "2.4.5"
webversion: "4.6.6"
configversion: "2.3.0"

dynamicimageroot: "http://jamessouth.me/images/imageprocessor/samples/"


# Collections

defaults:
  -
    scope:
      path: ""
    values:
      layout: "home"
  -
    scope:
      path: "imageprocessor"
    values:
      layout: "rootpage"
      navgroup: "imageprocessor"
      root: ImageProcessor
  -
    scope:
      path: "imageprocessor/imagefactory"
    values:
      navgroup: imageprocessor
      layout: method
      heading: Methods
      methodof: ImageFactory
  -
    scope:
      path: "imageprocessor/imagefactory/index.html"
    values:
      navgroup: imageprocessor
      layout: class
      class: ImageFactory
      methodof: null
  -
    scope:
      path: "imageprocessor/nativebinaryfactory"
    values:
      navgroup: imageprocessor
      layout: method
      heading: Methods
      methodof: NativeBinaryFactory
  -
    scope:
      path: "imageprocessor/nativebinaryfactory/index.html"
    values:
      navgroup: imageprocessor
      layout: class
      class: NativeBinaryFactory
      methodof: null
  -
    scope:
      path: "imageprocessor-web"
    values:
      layout: "rootpage"
      navgroup: "imageprocessor-web"
      root: ImageProcessorWeb
  -
    scope:
      path: "imageprocessor-web/imageprocessingmodule"
    values:
      navgroup: imageprocessor-web
      layout: method
      heading: Methods
      methodof: ImageProcessingModule
  -
    scope:
      path: "imageprocessor-web/imageprocessingmodule/index.html"
    values:
      navgroup: imageprocessor-web
      layout: class
      class: ImageProcessingModule
      methodof: null

gems:
  - jekyll-redirect-from

exclude:
  - README.md
  - CNAME
  - src
  - node_modules
  - Gemfile*
