image: Visual Studio 2017

# Prevent the double build when a branch has an active PR
skip_branch_with_pr: true

cache:
- packages -> **\packages.config

# Update any submodules we might add
before_build:
- git submodule -q update --init

# Custom build script
build_script:
- cmd: .\build\build.cmd

artifacts:
- path: '**\*.nupkg'